const productList=[
        {
            id:"1",
            name: 'boAt Airdopes 121v2 TWS Earbuds',
            image: '/images/boatHeadfone.jpg',
            description:
                'boAt Airdopes 121v2  Earbuds with Bluetooth V5.0, Immersive Audio, Up to 14H Total Playback, Voice Assistant, Easy Access Controls with Mic and  Ergonomic Design(Active Black) ',
            brand: 'Boat',
            category: 'Electronics',
            price: 20.99,
            countInStock: 10,
            rating: 4.5,
            numReviews: 12,
            amount: 1,
        },
        {
            id:"2",
            name: 'Micromax IN 1b (Purple, 32 GB)',
            image: './images/micromaxInB.jpg',
            description:
                'Say hello to  Micromax IN 1b smartphone, powerful MediaTek Helio G35 gaming processor and a 5000 mAh battery will pave the way for effortless multitasking  usage.',
            brand: 'Micromax',
            category: 'Electronics',
            price: 599.99,
            countInStock: 7,
            rating: 4.0,
            numReviews: 8,
            amount: 1,
        },
        {
            id:"3",
            name: 'Cannon EOS 80D DSLR Camera',
            image: './images/camera.jpg',
            description:
                'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
            brand: 'Cannon',
            category: 'Electronics',
            price: 929.99,
            countInStock: 5,
            rating: 3,
            numReviews: 12,
            amount: 1,
        },
        {
            id:"4",
            name: 'Sony Playstation 4 Pro White Version',
            image: './images/playstation.jpg',
            description:
                'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
            brand: 'Sony',
            category: 'Electronics',
            price: 399.99,
            countInStock: 11,
            rating: 5,
            numReviews: 12,
            amount: 1,
        },
        {
            id:"5",
            name: 'Logitech G-Series Gaming Mouse',
            image: './images/mouse.jpg',
            description:
                'Get a better handle on your games with  LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
            brand: 'Logitech',
            category: 'Electronics',
            price: 49.99,
            countInStock: 7,
            rating: 3.5,
            numReviews: 10,
            amount: 1,
        },
        {
            id:"6",
            name: 'Amazon Echo Dot 3rd Generation',
            image: './images/alexa.jpg',
            description:
                'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
            brand: 'Amazon',
            category: 'Electronics',
            price: 29.99,
            countInStock: 0,
            rating: 4,
            numReviews: 12,
            amount: 1,
        },
]

export default productList